# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.16"
  amd64: "ghcr.io/home-assistant/amd64-base:3.16"
  armhf: "ghcr.io/home-assistant/armhf-base:3.16"
  armv7: "ghcr.io/home-assistant/armv7-base:3.16"
  i386: "ghcr.io/home-assistant/i386-base:3.16"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Badger"
  org.opencontainers.image.description: "Add badge scan support."
  org.opencontainers.image.source: "https://github.com/BeardBucket/Home-Badger"
  org.opencontainers.image.licenses: "GPL v3"
args:
  TEMPIO_VERSION: "2021.09.0"
  DOCKER_BUILDKIT: "0"
