# https://home-assistant-china.github.io/developers/hassio/addon_config/
name: Badger add-on
version: "1.0.105"
slug: badger
description: Badger add-on adds badge scan support
url: "https://github.com/BeardBucket/Home-Badger/tree/main/badger"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: "ghcr.io/beardbucket/{arch}-addon-badger"
ports:
  3333/tcp: 3333
ports_description:
  3333/tcp: Web interface (Not required for Ingress)
homeassistant_api: true
auth_api: true
ingress: true
ingress_stream: true
panel_icon: mdi:text-box-outline
startup: "services"
# boot: "auto"
timeout: 60
