# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Badger add-on
version: "1.0.74"
slug: badger
description: Badger add-on adds badge scan support
url: "https://github.com/BeardBucket/Home-Badger/tree/main/badger"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: "ghcr.io/beardbucket/{arch}-addon-badger"
ports:
  80/tcp: 80
ports_description:
  80/tcp: Web interface (Not required for Ingress)
homeassistant_api: true
auth_api: true
ingress: true
ingress_stream: true
panel_icon: mdi:text-box-outline
startup: "services"
# boot: "auto"
