# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Badger add-on
version: "1.0.0"
slug: badger
description: Badger add-on adds badge scan support
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/beardbucket/{arch}-addon-badger"
